name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-version: ['7.1', '7.2', '7.3', '7.4']
        composer-parameters: ['', '--prefer-stable', '--prefer-lowest']

    runs-on: ${{ matrix.operating-system }}
    name: PHP ${{ matrix.php-version }} Test on ${{ matrix.operating-system }}
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer update --no-progress --no-suggest ${{ matrix.composer-parameters }}

      - name: Run test suite
        run: composer run-script test
